project:
  type: website
  output-dir: docs

website:
  title: "Ryan Keeney"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
        text: About
      - href: helpful_links.qmd
        text: Resources and Links
      - section: "NLP"
        contents: 
        - href: posts/avatar_vader.qmd
          text: VADAR Sentiment Scores
      - section: "Unsupervised Learning"
        contents: 
        - href: posts/PCA_eu_food.ipynb
          text: PCA | EU Food
        - href: posts/ISOMAP_faces.ipynb
          text: ISOMAP vs PCA
      - section: "Supervised Learning"
      - section: "Data Visualization"
      - section: "Applied Stats and EDA"
        contents: 
        - href: posts/anova_introduction.qmd
          text: ANOVA I

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
