project:
  type: website
  output-dir: docs

website:
  title: "Ryan Keeney"
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
        text: About
      - section: "NLP"
        contents: 
        - href: posts/avatar_vader.qmd
          text: VADAR Sentiment Scores
      - section: "Unsupervised Learning"
      - section: "Supervised Learning"
      - section: "Data Visualization"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



