project:
  type: website
  output-dir: docs

website:
  title: "Ryan Keeney"

  sidebar:
    title: Ryan Keeney
    logo: headshot.png
    style: "docked"
    search: true
    border: true
    alignment: "left"
    tools:
      - icon: twitter
        href: https://twitter.com/rbkeeney
      - icon: linkedin
        href: https://www.linkedin.com/in/ryan-brent-keeney/
      - icon: envelope
        href: mailto:keeney.ryan@gmail.com
    contents: 
      - href: index.qmd
        text: About Ryan
        icon: person
      - href: helpful_links.qmd
        text: Resources and Links
      - section: "Data Prep"
        contents: 
        - href: posts/tidymodels_recipes.qmd
          text: Preprocessing data in R
        - href: posts/missing_data.qmd
          text: Missing Data
      #- section: "Data Visualization"
        #contents:
      - section: "Supervised Learning"
        contents: 
        - href: posts/anova_introduction.qmd
          text: ANOVA 101
      - section: "Unsupervised Learning"
        contents: 
        - href: posts/PCA_eu_food.ipynb
          text: PCA with EU Foods
        - href: posts/ISOMAP_faces.ipynb
          text: ISOMAP vs PCA
      - section: "NLP"
        contents: 
        - href: posts/avatar_vader.qmd
          text: VADAR Sentiment Scores
        - href: posts/gibberish_detector.qmd
          text: Gibberish Detector

          
  page-footer: 
    left: "Copyright 2023, Ryan Keeney" 
    right: 
      - icon: twitter
        href: https://twitter.com/rbkeeney
      - icon: linkedin
        href: https://www.linkedin.com/in/ryan-brent-keeney/
      - icon: envelope
        href: mailto:keeney.ryan@gmail.com

format:
  html:
    theme:
      light: lumen
      #dark: darkly
    css: styles.css
    toc: true
